use_frameworks!

platform :ios, '10.0'

target 'MhQnOTPField_Example' do
  #pod 'MhQnOTPField', :path => '../'
	pod 'MhQnOTPField'

  target 'MhQnOTPField_Tests' do
    inherit! :search_paths

    
  end
end
